name: faza_app
description: A new Flutter project.

publish_to: "none"

version: 1.2.3+37


environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_places_flutter: ^2.0.6
  my_fatoorah: ^3.3.0
  get: ^4.6.5
  http: ^1.1.0
  dio: ^4.0.0
  # rename: ^2.1.1
  eva_icons_flutter: ^3.1.0
  empty_widget: ^0.0.5
  form_field_validator: ^1.1.0
  skeletons: ^0.0.3
  flutter_spinkit: ^5.2.0
  awesome_notifications: ^0.7.5-dev.3
  firebase_messaging: ^14.6.5
  firebase_core: ^2.15.0
  intl_phone_field: ^3.1.0
  flutter_quill: ^7.4.1
  cached_network_image: ^3.2.3
  pin_code_fields: ^8.0.1
  font_awesome_flutter: ^10.4.0
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.0.6
  like_button: ^2.0.5
  i18n_extension: ^9.0.2
  ndialog: ^4.3.0
  get_storage: ^2.1.1
  overlay_support: ^2.1.0
  # date_time_picker: ^2.1.0
  pull_to_refresh: ^2.0.0
  image_picker: ^1.0.2
  flutter_share: ^2.0.0
  datetime_picker_formfield_new: ^2.1.0
  url_launcher: ^6.1.11
  colorize_text_avatar: ^1.0.2
  carousel_slider: ^4.2.1
  persistent_bottom_nav_bar_v2: ^4.2.8
  flutter_slidable: ^3.0.0
  geolocator: ^10.0.0
  geocoding: ^2.1.0
  timeago: ^3.5.0
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2
  photo_view: ^0.14.0
  intl: ^0.18.0
  # vsc_quill_delta_to_html: ^1.0.3
  # device_info_plus: ^9.0.2
  # cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.4.0
  flutter_image_compress: ^2.0.3
  day_night_time_picker: ^1.2.0+2
  image_cropper: ^5.0.0
  bot_toast: ^4.0.4
  extended_phone_number_input: ^1.0.2
  sticky_headers: ^0.3.0+2
  http_parser: ^4.0.2
  webview_flutter: ^4.2.2
  lottie: ^2.6.0
  upgrader: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/logo.png"
  adaptive_icon_background:
flutter_native_splash:
  image: assets/splash.png

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/svg/
    - assets/flags/
  fonts:
    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
          weight: 900
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf
          weight: 700
          style: normal    
